# Generated by Django 3.2.3 on 2022-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogM', '0005_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='blogM/staticfile/'),
        ),
    ]
